import { Metadata } from "next";

export const metadata: Metadata = {
    title: "About | Savour Express",
    description: "Generated by create next app",
  };
const AboutPage = () => {
  return <div>AboutPage</div>;
};

export default AboutPage;
