import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Contact | Savour Express",
    description: "Generated by create next app",
  };

const ContactPage = () => {
  return (
    <div>ContactPage</div>
  )
}

export default ContactPage