import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Menu | Savour Express",
    description: "Generated by create next app",
  };

const MenuPage = () => {
  return (
    <div>MenuPage</div>
  )
}

export default MenuPage