import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Shop | Savour Express",
    description: "Generated by create next app",
  };
const ShopPage = () => {
  return (
    <div>ShopPage</div>
  )
}

export default ShopPage