import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Blog | Savour Express",
    description: "Generated by create next app",
  };

const BlogPage = () => {
  return (
    <div>BlogPage</div>
  )
}

export default BlogPage