import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Home | Savour Express",
    description: "Generated by create next app",
  };
const HomePage = () => {
  return <div>HomePage</div>;
};

export default HomePage;
